import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Coins, Database, ExternalLink, MessageSquare, RefreshCw, Search, ShieldCheck, Users, Wallet } from "lucide-react";
import { endpoints } from "../api";
import { Button, Modal, Notice, Skeleton, money, shortAddress } from "../components/UI";

export function AdminPage() {
  const [tab, setTab] = useState("overview"); const [overview, setOverview] = useState(null); const [users, setUsers] = useState([]); const [tickets, setTickets] = useState([]); const [operations, setOperations] = useState([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [grantUser, setGrantUser] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(""); const results = await Promise.allSettled([endpoints.admin.overview(), endpoints.admin.users(query), endpoints.admin.tickets(), endpoints.admin.operations()]); if (results[0].status === "fulfilled") setOverview(results[0].value); else setError(results[0].reason.message); if (results[1].status === "fulfilled") setUsers(results[1].value?.users || results[1].value?.items || (Array.isArray(results[1].value) ? results[1].value : [])); if (results[2].status === "fulfilled") setTickets(results[2].value?.tickets || results[2].value?.items || (Array.isArray(results[2].value) ? results[2].value : [])); if (results[3].status === "fulfilled") setOperations(results[3].value?.operations || results[3].value?.items || (Array.isArray(results[3].value) ? results[3].value : [])); setLoading(false); }, [query]);
  useEffect(() => { load(); }, [load]);
  const metrics = useMemo(() => [
    { label: "Total users", value: overview?.totalUsers ?? overview?.users ?? 0, icon: Users },
    { label: "Credits outstanding", value: Number(overview?.creditsOutstanding ?? overview?.totalCredits ?? 0).toLocaleString(), icon: Coins },
    { label: "Created coins", value: overview?.createdCoins ?? overview?.coins ?? 0, icon: Wallet },
    { label: "Open tickets", value: overview?.openTickets ?? tickets.filter((item) => item.status === "open").length, icon: MessageSquare },
  ], [overview, tickets]);
  if (loading) return <div className="page-loading"><Skeleton lines={8}/></div>;
  return <div className="standard-page admin-page"><header className="page-title"><div><p>ADMINISTRATION</p><h1>PAN operations</h1><span>Manage users, credits, launches, support and background systems.</span></div><Button variant="secondary" onClick={load}><RefreshCw/>Refresh</Button></header>{error ? <Notice onClose={() => setError("")}>{error}</Notice> : null}<nav className="admin-tabs">{[["overview","Overview",Activity],["users","Users",Users],["tickets","Support",MessageSquare],["operations","Operations",Database]].map(([id,label,Icon]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><Icon/>{label}</button>)}</nav>
    {tab === "overview" ? <><section className="metric-grid admin-metrics">{metrics.map(({ label, value, icon: Icon }) => <article className="metric-card" key={label}><span><Icon/></span><p>{label}</p><strong>{value}</strong></article>)}</section><section className="admin-overview-grid"><article><div className="section-heading"><div><h2>Platform funds</h2><p>Tracked balances across operational systems.</p></div><Wallet/></div><dl><div><dt>Operational ETH</dt><dd>{Number(overview?.operationalEth || 0).toFixed(5)} ETH</dd></div><div><dt>PAN received and burned</dt><dd>{Number(overview?.panBurned || 0).toLocaleString()} PAN</dd></div><div><dt>AI spend today</dt><dd>{money(overview?.aiSpendTodayUsd)}</dd></div></dl></article><article><div className="section-heading"><div><h2>System status</h2><p>Important service health and queue pressure.</p></div><ShieldCheck/></div><dl><div><dt>Database</dt><dd className="green">{overview?.databaseStatus || "Healthy"}</dd></div><div><dt>Queue depth</dt><dd>{overview?.queueDepth || 0}</dd></div><div><dt>Failed jobs</dt><dd className={overview?.failedJobs ? "red" : ""}>{overview?.failedJobs || 0}</dd></div></dl></article></section></> : null}
    {tab === "users" ? <section className="admin-table-card"><header><div><h2>Users</h2><p>Review balances, wallets and account state.</p></div><form onSubmit={(e) => { e.preventDefault(); load(); }} className="search-box"><Search/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search email or username"/></form></header><div className="data-table"><div className="table-head users-head"><span>User</span><span>Credits</span><span>Wallet</span><span>Status</span><span></span></div>{users.map((user) => <div className="table-row users-row" key={user.id}><span><i className="user-dot">{(user.username || user.email || "U")[0].toUpperCase()}</i><b>{user.username || user.email}<small>{user.email}</small></b></span><span>{Number(user.creditBalance ?? user.credits ?? 0).toLocaleString()}</span><span className="mono">{shortAddress(user.walletAddress)}</span><span><em className={`status-pill ${user.status === "active" ? "live" : "draft"}`}>{user.status || "active"}</em></span><span><Button variant="ghost" onClick={() => setGrantUser(user)}><Coins/>Adjust credits</Button></span></div>)}</div></section> : null}
    {tab === "tickets" ? <section className="admin-table-card"><header><div><h2>Support tickets</h2><p>Open a ticket to read and reply from the support workspace.</p></div></header><div className="data-table"><div className="table-head"><span>Ticket</span><span>User</span><span>Status</span><span>Updated</span></div>{tickets.map((ticket) => <div className="table-row" key={ticket.id}><span><b>{ticket.subject || ticket.title}</b></span><span>{ticket.userEmail || ticket.username}</span><span><em className={`status-pill ${ticket.status === "open" ? "live" : "draft"}`}>{ticket.status}</em></span><span>{new Date(ticket.updatedAt || ticket.createdAt).toLocaleString()}</span></div>)}</div></section> : null}
    {tab === "operations" ? <section className="admin-table-card"><header><div><h2>Operational jobs</h2><p>Conversions, AI runs, launches, exports and monitoring jobs.</p></div></header><div className="operation-list">{operations.map((operation) => <article key={operation.id}><span className={`operation-icon ${operation.status}`}>{operation.status === "failed" ? <AlertTriangle/> : <Activity/>}</span><div><strong>{operation.type || operation.name}</strong><p>{operation.message || operation.description}</p><small>{new Date(operation.updatedAt || operation.createdAt).toLocaleString()}</small></div><em className={`status-pill ${operation.status === "completed" ? "live" : "draft"}`}>{operation.status}</em>{operation.url ? <a href={operation.url}><ExternalLink/></a> : null}</article>)}</div></section> : null}
    {grantUser ? <GrantModal user={grantUser} onClose={() => setGrantUser(null)} onDone={() => { setGrantUser(null); load(); }} /> : null}
  </div>;
}

function GrantModal({ user, onClose, onDone }) {
  const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const submit = async () => { setLoading(true); setError(""); try { await endpoints.admin.grant(user.id, Number(amount), reason); onDone(); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  return <Modal title="Adjust user credits" subtitle={`${user.username || user.email} currently has ${Number(user.creditBalance ?? user.credits ?? 0).toLocaleString()} credits.`} onClose={onClose}><div className="modal-body">{error ? <Notice>{error}</Notice> : null}<label className="field"><span>Credit adjustment</span><input type="number" step="1" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Use a negative number to deduct"/></label><label className="field"><span>Internal reason</span><textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Why is this adjustment needed?"/></label><div className="modal-actions"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button loading={loading} disabled={!Number.isFinite(Number(amount)) || Number(amount) === 0 || reason.trim().length < 3} onClick={submit}>Apply adjustment</Button></div></div></Modal>;
}
