import { useEffect, useMemo, useState } from "react";
import { ArrowDownToLine, ArrowUpRight, Check, Clipboard, Coins, Copy, Flame, History, RefreshCw, ShieldCheck, Wallet } from "lucide-react";
import { endpoints } from "../api";
import { Button, Modal, Notice, Skeleton, money, shortAddress } from "../components/UI";

export function CreditsPage() {
  const [data, setData] = useState(null); const [wallets, setWallets] = useState([]); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [buyOpen, setBuyOpen] = useState(false); const [withdrawOpen, setWithdrawOpen] = useState(false); const [method, setMethod] = useState("pan"); const [amount, setAmount] = useState(100); const [working, setWorking] = useState(false); const [intent, setIntent] = useState(null); const [provisioning, setProvisioning] = useState(false);
  const operational = wallets.find((item) => item.role === "operations" || ["operational", "spending", "launch"].includes(item.type)) || data?.operationalWallet || {};
  const payment = wallets.find((item) => item.role === "credit_intake" || ["payment", "credits", "conversion"].includes(item.type)) || data?.paymentWallet || {};

  const load = async () => {
    setLoading(true);
    const results = await Promise.allSettled([endpoints.credits.summary(), endpoints.wallets.list(), endpoints.credits.history()]);
    if (results[0].status === "fulfilled") setData(results[0].value);
    else setError(results[0].reason.message);
    if (results[1].status === "fulfilled") setWallets(results[1].value?.wallets || results[1].value?.items || (Array.isArray(results[1].value) ? results[1].value : []));
    if (results[2].status === "fulfilled") setHistory(results[2].value?.transactions || results[2].value?.items || (Array.isArray(results[2].value) ? results[2].value : []));
    setLoading(false);
  };
  useEffect(() => { load(); }, []);

  const provisionWallets = async () => {
    setProvisioning(true); setError("");
    try {
      const result = await endpoints.wallets.provision();
      setWallets(result?.wallets || result?.items || (Array.isArray(result) ? result : []));
      await load();
    } catch (requestError) { setError(requestError.message); }
    finally { setProvisioning(false); }
  };

  const credits = Number(data?.creditBalance ?? data?.credits ?? data?.balance ?? 0);
  const panPrice = Number(data?.panUsdPrice ?? data?.price?.panUsd ?? 0);
  const estimatedUsd = useMemo(() => method === "pan" ? Number(amount) * panPrice : Number(data?.ethUsdPrice || 0) * Number(amount), [method, amount, panPrice, data]);

  const createPurchase = async () => { setWorking(true); setError(""); try { const result = await endpoints.credits.purchase({ asset: method === "pan" ? "PAN" : "ETH", amount: Number(amount), expectedCredits: method === "pan" ? Number(amount) : undefined }); setIntent(result?.intent ? { ...result.intent, depositAddress: result.depositAddress } : result); } catch (e) { setError(e.message); } finally { setWorking(false); } };
  const copy = async (text) => navigator.clipboard.writeText(text || "");

  if (loading) return <div className="page-loading"><Skeleton lines={7}/></div>;

  return <div className="standard-page credits-page"><header className="page-title"><div><p>ACCOUNT FUNDS</p><h1>Credits & wallet</h1><span>Buy AI credits and manage withdrawable launch ETH.</span></div><Button onClick={() => setBuyOpen(true)}><Coins/>Buy credits</Button></header>{error ? <Notice onClose={() => setError("")}>{error}</Notice> : null}
    <section className="metric-grid"><article className="metric-card featured"><span><Coins/></span><p>PAN credits</p><strong>{credits.toLocaleString()}</strong><small>1 burned PAN token = 1 non-withdrawable credit</small></article><article className="metric-card"><span><Wallet/></span><p>Withdrawable ETH</p><strong>{Number(operational.ethBalance || operational.balance || data?.ethBalance || 0).toFixed(5)} ETH</strong><small>{money((operational.ethBalance || data?.ethBalance || 0) * (data?.ethUsdPrice || 0))} estimated value</small></article><article className="metric-card"><span><RefreshCw/></span><p>PAN market price</p><strong>{money(panPrice, 6)}</strong><small>Backend price snapshot · refreshed every 30 seconds</small></article></section>
    <section className="wallet-section"><div className="section-heading"><div><h2>Your account wallets</h2><p>PAN separates credit conversion from withdrawable operational funds.</p></div>{payment.address && operational.address ? <Button variant="secondary" onClick={() => setWithdrawOpen(true)}><ArrowUpRight/>Withdraw ETH</Button> : <Button loading={provisioning} onClick={provisionWallets}><Wallet/>Create account wallets</Button>}</div>{!payment.address || !operational.address ? <Notice>Your encrypted account wallets have not been provisioned yet. Create them once, then use the payment wallet for credit purchases and the operational wallet for launch funding.</Notice> : null}{data?.token?.contractAddress ? <Notice type="success">Accepted PAN token contract: <code>{data.token.contractAddress}</code>. Always create a purchase intent before sending PAN or ETH to the credit wallet.</Notice> : null}<div className="wallet-grid"><article><span className="wallet-icon"><Flame/></span><div><small>CREDIT PAYMENT WALLET</small><h3>{payment.address ? shortAddress(payment.address) : "Not available"}</h3><p>Send PAN or ETH here only after creating a credit purchase. PAN is burned; ETH triggers the configured buyback.</p></div><button disabled={!payment.address} onClick={() => copy(payment.address)}><Copy/></button></article><article><span className="wallet-icon"><Wallet/></span><div><small>OPERATIONAL ETH WALLET</small><h3>{operational.address ? shortAddress(operational.address) : "Not available"}</h3><p>Top up at any time for launches and project fees. Unreserved ETH remains withdrawable.</p></div><button disabled={!operational.address} onClick={() => copy(operational.address)}><Copy/></button></article></div></section>
    <section className="history-section"><div className="section-heading"><div><h2>Credit activity</h2><p>Confirmed purchases, usage, refunds and administrator adjustments.</p></div><History/></div><div className="data-table"><div className="table-head"><span>Activity</span><span>Status</span><span>Credits</span><span>Date</span></div>{history.length ? history.map((item) => <div className="table-row" key={item.id}><span><i className={Number(item.amount || item.credits) >= 0 ? "positive" : "negative"}>{Number(item.amount || item.credits) >= 0 ? <ArrowDownToLine/> : <ArrowUpRight/>}</i><b>{item.description || item.entryType || item.type || "Credit activity"}</b></span><span><em className={`status-pill ${item.status === "confirmed" || item.status === "completed" ? "live" : "draft"}`}>{item.status || "completed"}</em></span><span className={Number(item.amount || item.credits) >= 0 ? "green" : ""}>{Number(item.amount || item.credits) >= 0 ? "+" : ""}{Number(item.amount || item.credits || 0).toLocaleString()}</span><span>{item.createdAt || item.date ? new Date(item.createdAt || item.date).toLocaleDateString() : "Not available"}</span></div>) : <div className="table-empty">No credit activity yet.</div>}</div></section>
    {buyOpen ? <Modal title="Buy PAN credits" subtitle="Credits are final and cannot be withdrawn back into PAN tokens." onClose={() => { setBuyOpen(false); setIntent(null); }}><div className="modal-body">{intent ? <div className="payment-intent"><span><Check/></span><h3>Purchase intent created</h3><p>Send exactly the specified amount to the payment wallet. PAN will detect confirmations and credit your account.</p><label><small>Amount</small><strong>{intent.requestedAmountDisplay || intent.amount || amount} {(intent.paymentAsset || intent.asset || method).toUpperCase()}</strong></label><label><small>Deposit address</small><code>{intent.depositAddress || intent.address || payment.address}</code><button onClick={() => copy(intent.depositAddress || intent.address || payment.address)}><Clipboard/></button></label><small>Reference: {intent.id || intent.intentId}</small><Button onClick={() => { setBuyOpen(false); setIntent(null); load(); }}>Done</Button></div> : <><div className="payment-methods"><button className={method === "pan" ? "active" : ""} onClick={() => { setMethod("pan"); setAmount(100); }}><Flame/><strong>Pay with PAN</strong><small>1 PAN = 1 credit · tokens burned</small></button><button className={method === "eth" ? "active" : ""} onClick={() => { setMethod("eth"); setAmount(0.01); }}><Wallet/><strong>Pay with ETH</strong><small>Market-rate credits · automatic buyback</small></button></div><label className="field"><span>Amount in {method === "pan" ? "PAN" : "ETH"}</span><input type="number" min={method === "pan" ? 1 : 0.0001} step={method === "pan" ? 1 : 0.001} value={amount} onChange={(e) => setAmount(e.target.value)}/></label><div className="purchase-estimate"><span>Estimated value</span><strong>{money(estimatedUsd)}</strong><small>The backend locks a price snapshot when the intent is created.</small></div><Notice type="success"><ShieldCheck/>Credits are issued only after the on-chain payment reaches the required confirmations.</Notice><div className="modal-actions"><Button variant="ghost" onClick={() => setBuyOpen(false)}>Cancel</Button><Button loading={working} disabled={Number(amount) <= 0} onClick={createPurchase}>Create purchase</Button></div></>}</div></Modal> : null}
    {withdrawOpen ? <WithdrawModal wallet={operational} onClose={() => setWithdrawOpen(false)} onDone={load} /> : null}
  </div>;
}

function WithdrawModal({ wallet, onClose, onDone }) {
  const [address, setAddress] = useState(""); const [amount, setAmount] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [done, setDone] = useState("");
  const available = Number(wallet.availableBalance ?? wallet.ethBalance ?? wallet.balance ?? 0);
  const submit = async () => { setLoading(true); setError(""); try { const data = await endpoints.wallets.withdraw({ walletId: wallet.id, address, amountEth: Number(amount) }); setDone(data?.transactionHash || data?.txHash || "Withdrawal submitted"); onDone(); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  return <Modal title="Withdraw operational ETH" subtitle="Funds reserved by an active launch or purchase cannot be withdrawn." onClose={onClose}><div className="modal-body">{error ? <Notice>{error}</Notice> : null}{done ? <Notice type="success">{done}</Notice> : null}<label className="field"><span>Destination address</span><input value={address} onChange={(e) => setAddress(e.target.value.trim())} placeholder="0x…"/></label><label className="field"><span>Amount in ETH</span><div className="amount-input"><input type="number" min="0" max={available} step="0.0001" value={amount} onChange={(e) => setAmount(e.target.value)}/><button onClick={() => setAmount(String(available))}>MAX</button></div><small>Available: {available.toFixed(6)} ETH</small></label><div className="modal-actions"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button loading={loading} disabled={!/^0x[a-fA-F0-9]{40}$/.test(address) || Number(amount) <= 0 || Number(amount) > available} onClick={submit}>Withdraw ETH</Button></div></div></Modal>;
}
