import { useEffect, useState } from "react";
import { Bot, Check, GitBranch, Link as LinkIcon, MonitorUp, ShieldCheck, User, Wallet, Zap } from "lucide-react";
import { endpoints } from "../api";
import { useAuth } from "../auth";
import { Button, Notice, Skeleton, shortAddress } from "../components/UI";

const modes = [
  { id: "low", name: "Low", text: "Quick details, summaries and simple edits", model: "Claude Haiku" },
  { id: "medium", name: "Medium", text: "Everyday project work and normal website changes", model: "Claude Sonnet" },
  { id: "high", name: "High", text: "Complex builds, debugging and longer tool runs", model: "Claude Sonnet · high effort" },
  { id: "extra_high", name: "Extra high", text: "Hard architecture and failure recovery", model: "Claude Opus" },
];

export function SettingsPage() {
  const { user, refresh } = useAuth();
  const [account, setAccount] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [form, setForm] = useState({ username: "", defaultPerformance: "medium", terminal: "gmgn", askWhenUncertain: true });
  const [github, setGithub] = useState(null);
  useEffect(() => { Promise.allSettled([endpoints.account.summary(), endpoints.sites.githubStatus()]).then(([accountResult, githubResult]) => { if (accountResult.status === "fulfilled") { const value = accountResult.value?.account || accountResult.value; setAccount(value); setForm({ username: value.username || user?.username || "", defaultPerformance: value.defaultPerformance || "medium", terminal: value.terminal || "gmgn", askWhenUncertain: value.askWhenUncertain !== false }); } else setError(accountResult.reason.message); if (githubResult.status === "fulfilled") setGithub(githubResult.value); }).finally(() => setLoading(false)); }, [user]);
  const save = async () => { setSaving(true); setError(""); setSuccess(""); try { await endpoints.account.update(form); await refresh(); setSuccess("Settings saved."); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const connectWallet = async () => { setError(""); if (!window.ethereum) return setError("Install an Ethereum-compatible wallet extension to continue."); try { const [address] = await window.ethereum.request({ method: "eth_requestAccounts" }); const challenge = await endpoints.wallets.connectChallenge({ address, chain: "ethereum" }); const message = challenge.message || challenge.challenge; const signature = await window.ethereum.request({ method: "personal_sign", params: [message, address] }); await endpoints.wallets.connectVerify({ address, signature, challengeId: challenge.id || challenge.challengeId }); setAccount((old) => ({ ...old, connectedWalletAddress: address })); setSuccess("External wallet connected."); } catch (e) { setError(e.message || "Wallet connection was cancelled."); } };
  if (loading) return <div className="page-loading"><Skeleton lines={7}/></div>;
  return <div className="standard-page settings-page"><header className="page-title"><div><p>ACCOUNT</p><h1>Settings</h1><span>Control your identity, AI defaults and connected services.</span></div><Button loading={saving} onClick={save}>Save changes</Button></header>{error ? <Notice onClose={() => setError("")}>{error}</Notice> : null}{success ? <Notice type="success" onClose={() => setSuccess("")}>{success}</Notice> : null}
    <div className="settings-layout"><nav><a href="#profile"><User/>Profile</a><a href="#ai"><Bot/>AI performance</a><a href="#wallet"><Wallet/>Wallets</a><a href="#services"><LinkIcon/>Connected services</a><a href="#terminal"><MonitorUp/>Terminal</a></nav><div className="settings-content">
      <section id="profile" className="settings-card"><div className="settings-heading"><span><User/></span><div><h2>Profile</h2><p>Your public account identity.</p></div></div><div className="profile-editor"><span className="profile-avatar">{(form.username || user?.email || "P").slice(0,1).toUpperCase()}</span><label className="field"><span>Username</span><input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })}/><small>Email: {user?.email || account?.email}</small></label></div></section>
      <section id="ai" className="settings-card"><div className="settings-heading"><span><Bot/></span><div><h2>AI performance</h2><p>Choose the default balance between capability and credit usage.</p></div></div><div className="mode-list">{modes.map((mode) => <button key={mode.id} className={form.defaultPerformance === mode.id ? "active" : ""} onClick={() => setForm({ ...form, defaultPerformance: mode.id })}><span><Zap/></span><div><strong>{mode.name}</strong><p>{mode.text}</p><small>{mode.model}</small></div><i>{form.defaultPerformance === mode.id ? <Check/> : null}</i></button>)}</div><label className="toggle-row"><div><strong>Ask when uncertain</strong><small>PAN pauses for missing or ambiguous details instead of assuming.</small></div><input type="checkbox" checked={form.askWhenUncertain} onChange={(e) => setForm({ ...form, askWhenUncertain: e.target.checked })}/><span/></label></section>
      <section id="wallet" className="settings-card"><div className="settings-heading"><span><Wallet/></span><div><h2>External wallet</h2><p>Use wallet confirmations to sign launches and on-chain operations.</p></div></div><div className="connection-row"><div><span className="connection-icon"><Wallet/></span><div><strong>{account?.connectedWalletAddress ? shortAddress(account.connectedWalletAddress) : "No wallet connected"}</strong><small>{account?.connectedWalletAddress ? "Ethereum wallet ready for confirmations" : "Connect MetaMask, Phantom EVM or another compatible wallet"}</small></div></div><Button variant="secondary" onClick={connectWallet}>{account?.connectedWalletAddress ? "Reconnect" : "Connect wallet"}</Button></div><Notice type="success"><ShieldCheck/>PAN requests signatures from your wallet and never needs its private key.</Notice></section>
      <section id="services" className="settings-card"><div className="settings-heading"><span><LinkIcon/></span><div><h2>Connected services</h2><p>Services used for exports and deployment.</p></div></div><div className="connection-row"><div><span className="connection-icon"><GitBranch/></span><div><strong>GitHub</strong><small>{github?.connected ? `Connected as ${github.username || github.login || "GitHub user"}` : "Not connected"}</small></div></div>{github?.connected ? <span className="connected"><Check/>Connected</span> : <a className="button button-secondary" href={endpoints.sites.githubConnectUrl}>Connect</a>}</div></section>
      <section id="terminal" className="settings-card"><div className="settings-heading"><span><MonitorUp/></span><div><h2>Coin terminal</h2><p>Choose where “View coin” opens after launch.</p></div></div><label className="field"><span>Default terminal</span><select value={form.terminal} onChange={(e) => setForm({ ...form, terminal: e.target.value })}><option value="gmgn">GMGN</option><option value="dexscreener">DexScreener</option><option value="defined">Defined</option></select></label></section>
    </div></div>
  </div>;
}
