import { useCallback, useEffect, useState } from "react";
import { Check, ChevronRight, LifeBuoy, Lock, MessageSquare, Plus, Send } from "lucide-react";
import { endpoints } from "../api";
import { Button, EmptyState, Modal, Notice, Skeleton } from "../components/UI";

export function SupportPage() {
  const [tickets, setTickets] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [createOpen, setCreateOpen] = useState(false); const [error, setError] = useState(""); const [working, setWorking] = useState(false); const [reply, setReply] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const data = await endpoints.support.list(); const list = data?.tickets || data?.items || (Array.isArray(data) ? data : []); setTickets(list); setSelected((old) => old ? list.find((item) => item.id === old.id) || old : null); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const openCount = tickets.filter((item) => !["closed","resolved"].includes(item.status)).length;
  const sendReply = async () => { if (!reply.trim()) return; setWorking(true); try { await endpoints.support.reply(selected.id, { message: reply.trim() }); setReply(""); await load(); } catch (e) { setError(e.message); } finally { setWorking(false); } };
  const close = async () => { setWorking(true); try { await endpoints.support.close(selected.id); await load(); setSelected((old) => ({ ...old, status: "closed" })); } catch (e) { setError(e.message); } finally { setWorking(false); } };
  if (loading) return <div className="page-loading"><Skeleton lines={7}/></div>;
  return <div className="standard-page support-page"><header className="page-title"><div><p>HELP CENTER</p><h1>Support</h1><span>Open up to three tickets and continue the conversation with PAN support.</span></div><Button disabled={openCount >= 3} onClick={() => setCreateOpen(true)}><Plus/>New ticket</Button></header>{error ? <Notice onClose={() => setError("")}>{error}</Notice> : null}{openCount >= 3 ? <Notice>You already have three open tickets. Close one before opening another.</Notice> : null}
    <div className="ticket-layout"><section className="ticket-list"><header><h2>Your tickets</h2><span>{openCount}/3 open</span></header>{tickets.length ? tickets.map((ticket) => <button key={ticket.id} className={selected?.id === ticket.id ? "active" : ""} onClick={() => setSelected(ticket)}><span className={`ticket-icon ${ticket.status}`}><MessageSquare/></span><div><strong>{ticket.subject || ticket.title}</strong><p>{ticket.lastMessage || ticket.preview || ticket.message || ticket.category}</p><small>{new Date(ticket.updatedAt || ticket.createdAt).toLocaleString()}</small></div><em>{ticket.status}</em><ChevronRight/></button>) : <EmptyState icon={LifeBuoy} title="No support tickets" text="When you need help, open a ticket and an administrator can reply here." />}</section><section className="ticket-thread">{selected ? <><header><div><small>TICKET #{String(selected.id).slice(-6)}</small><h2>{selected.subject || selected.title}</h2><span className={`status-pill ${selected.status === "closed" ? "draft" : "live"}`}>{selected.status}</span></div>{selected.status !== "closed" ? <Button variant="ghost" loading={working} onClick={close}><Lock/>Close ticket</Button> : null}</header><div className="thread-feed">{(selected.messages || []).map((message) => <article className={message.isAdmin || message.role === "admin" || message.senderRole === "admin" ? "admin-message" : "customer-message"} key={message.id}><small>{message.isAdmin || message.role === "admin" || message.senderRole === "admin" ? "PAN SUPPORT" : "YOU"}</small><p>{message.body || message.message || message.content}</p><time>{new Date(message.createdAt).toLocaleString()}</time></article>)}{!selected.messages?.length ? <p className="thread-empty">No messages were returned for this ticket.</p> : null}</div>{selected.status !== "closed" ? <div className="thread-compose"><textarea value={reply} onChange={(e) => setReply(e.target.value)} placeholder="Write a reply…"/><Button loading={working} disabled={!reply.trim()} onClick={sendReply}><Send/>Send</Button></div> : <div className="closed-thread"><Check/>This ticket is closed.</div>}</> : <EmptyState icon={MessageSquare} title="Select a ticket" text="Choose a ticket to view its conversation." />}</section></div>
    {createOpen ? <NewTicket onClose={() => setCreateOpen(false)} onCreated={(ticket) => { setTickets((old) => [ticket, ...old]); setSelected(ticket); setCreateOpen(false); }} /> : null}
  </div>;
}

function NewTicket({ onClose, onCreated }) {
  const [form, setForm] = useState({ subject: "", category: "technical", message: "" }); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const create = async () => { setLoading(true); setError(""); try { const data = await endpoints.support.create(form); onCreated(data?.ticket || data); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  return <Modal title="Open a support ticket" subtitle="Include enough detail for the support team to reproduce the problem." onClose={onClose}><div className="modal-body">{error ? <Notice>{error}</Notice> : null}<label className="field"><span>Subject</span><input value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} placeholder="What do you need help with?"/></label><label className="field"><span>Category</span><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option value="technical">Technical problem</option><option value="billing">Credits or billing</option><option value="wallet">Wallet or transaction</option><option value="launch">Coin launch</option><option value="website">Website builder</option></select></label><label className="field"><span>Message</span><textarea rows="6" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Describe what happened, what you expected and any error shown."/></label><div className="modal-actions"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button loading={loading} disabled={!form.subject.trim() || form.message.trim().length < 10} onClick={create}>Open ticket</Button></div></div></Modal>;
}
